language: php
dist: trusty
matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      dist: xenial
    - php: 8.0
      dist: xenial
  fast_finish: true
install:
  - composer install
before_script:
  - |
    echo "TRAVIS_PHP_VERSION:" $TRAVIS_PHP_VERSION;
    php -v;
    php -r 'echo "PHP: ".PHP_VERSION."\n";';
    if [ $(echo "$TRAVIS_PHP_VERSION >= 8.0" | bc -l) -eq 1 ]; then
      echo using PHPUnit 9.x
      curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-9.phar
    elif [ $(echo "$TRAVIS_PHP_VERSION >= 7.2" | bc -l) -eq 1 ]; then
      echo using PHPUnit 7.5.2
      curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-7.5.2.phar;
    fi
