language: php
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
matrix:
  fast_finish: true
install:
  - composer install
before_script:
  - |
    echo "TRAVIS_PHP_VERSION:" $TRAVIS_PHP_VERSION;
    php -v;
    php -r 'echo "PHP: ".PHP_VERSION."\n";';
    if [ $(echo "$TRAVIS_PHP_VERSION >= 7.2" | bc -l) -eq 1 ]; then
      echo using PHPUnit 7.5.2
      curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-7.5.2.phar;
    fi
